<?php
/**
 * Build the explainer browser fixture from the widgets' own render().
 *
 * The other fixtures in this folder are hand-written markup. This one is not,
 * on purpose: the thing worth proving here is that the PHP emits the section
 * the design asks for, so the page is generated by calling render() with a
 * settings array and capturing what comes out.
 *
 * Usage, from the repository root:
 *
 *   php tests/browser/explainer-fixture.php > tests/browser/explainer.html
 *
 * tests/ is excluded from the release zip, so none of this ships.
 *
 * @package ErudaToolkit
 */

namespace {

define( 'ABSPATH', dirname( __DIR__, 2 ) . '/' );

require_once dirname( __DIR__ ) . '/stubs/elementor.php';

if ( ! function_exists( 'esc_html__' ) ) {
	/**
	 * @param string $text   Text.
	 * @param string $domain Domain.
	 * @return string
	 */
	function esc_html__( $text, $domain = 'default' ) { // phpcs:ignore
		return htmlspecialchars( $text, ENT_QUOTES, 'UTF-8' );
	}
}

if ( ! function_exists( 'esc_html' ) ) {
	/**
	 * @param string $text Text.
	 * @return string
	 */
	function esc_html( $text ) { // phpcs:ignore
		return htmlspecialchars( (string) $text, ENT_QUOTES, 'UTF-8' );
	}
}

if ( ! function_exists( 'esc_attr' ) ) {
	/**
	 * @param string $text Text.
	 * @return string
	 */
	function esc_attr( $text ) { // phpcs:ignore
		return htmlspecialchars( (string) $text, ENT_QUOTES, 'UTF-8' );
	}
}

if ( ! function_exists( 'esc_url' ) ) {
	/**
	 * @param string $url URL.
	 * @return string
	 */
	function esc_url( $url ) { // phpcs:ignore
		return htmlspecialchars( (string) $url, ENT_QUOTES, 'UTF-8' );
	}
}

require_once dirname( __DIR__, 2 ) . '/modules/explainer/class-explainer-content.php';
}


/**
 * The panel category the widget names at registration time.
 */
namespace ErudaToolkit {
	if ( ! class_exists( '\ErudaToolkit\Panel_Category' ) ) {
		/**
		 * Stand-in for the real category.
		 */
		class Panel_Category {
			const SLUG = 'eruda-toolkit';
		}
	}
}

namespace ErudaToolkit\Modules\Explainer {
	if ( ! class_exists( '\ErudaToolkit\Modules\Explainer\Explainer_Module' ) ) {
		/**
		 * Stand-in for the module, for its asset handles.
		 */
		final class Explainer_Module {
			const STYLE_HANDLE  = 'eexp-split-explainer';
			const SCRIPT_HANDLE = 'eexp-split-explainer';
		}
	}
}

namespace {

	require_once dirname( __DIR__, 2 ) . '/modules/explainer/widgets/class-split-slab-widget.php';
	require_once dirname( __DIR__, 2 ) . '/modules/explainer/widgets/class-comparison-ledger-widget.php';

	/**
	 * Everything a fixture widget needs on top of the real one.
	 */
	trait Fixture_Widget {

		/**
		 * Settings to render.
		 *
		 * @var array
		 */
		private $fixture = array();

		/**
		 * @param array $settings Settings.
		 */
		public function __construct( $settings = array() ) {
			$this->fixture = $settings;
		}

		/**
		 * @return array
		 */
		public function get_settings_for_display() {
			return $this->fixture;
		}

		/**
		 * Render attributes, enough for the one link this widget prints.
		 *
		 * @var array
		 */
		private $attributes = array();

		/**
		 * @param string $key   Element key.
		 * @param string $name  Attribute.
		 * @param string $value Value.
		 */
		public function add_render_attribute( $key, $name = null, $value = null ) {
			$this->attributes[ $key ][ $name ][] = $value;
		}

		/**
		 * @param string $key      Element key.
		 * @param array  $link     Link control value.
		 */
		public function add_link_attributes( $key, $link ) {
			if ( ! empty( $link['url'] ) ) {
				$this->attributes[ $key ]['href'][] = $link['url'];
			}

			if ( ! empty( $link['is_external'] ) ) {
				$this->attributes[ $key ]['target'][] = '_blank';
			}
		}

		/**
		 * @param string $key Element key.
		 */
		public function print_render_attribute_string( $key ) {
			if ( empty( $this->attributes[ $key ] ) ) {
				return;
			}

			$out = array();

			foreach ( $this->attributes[ $key ] as $name => $values ) {
				$out[] = sprintf( '%s="%s"', $name, esc_attr( implode( ' ', $values ) ) );
			}

			echo implode( ' ', $out ); // phpcs:ignore
		}

		/**
		 * Render and return, rather than print.
		 *
		 * @return string
		 */
		public function to_html() {
			ob_start();
			$this->render();

			return (string) ob_get_clean();
		}
	}

	/**
	 * The slab, rendering whatever settings it is handed.
	 */
	class Slab_Fixture extends \ErudaToolkit\Modules\Explainer\Widgets\Split_Slab_Widget {
		use Fixture_Widget;
	}

	/**
	 * The ledger, the same way.
	 */
	class Ledger_Fixture extends \ErudaToolkit\Modules\Explainer\Widgets\Comparison_Ledger_Widget {
		use Fixture_Widget;
	}

	/**
	 * Repeater rows, the shape Elementor hands over.
	 *
	 * @param array $rows Rows.
	 * @return array
	 */
	function rows( array $rows ) {
		return $rows;
	}

	/*
	 * Where the pictures and the module's assets sit, relative to the page.
	 * The defaults are right for this folder; both can be pointed elsewhere so
	 * the same fixture can be staged outside the repository for screenshots.
	 */
	$images = getenv( 'EEXP_FIXTURE_IMAGES' );
	$images = false === $images || '' === $images ? '../../../../Documents/ThermStar/1-plan/sections/images/' : $images;

	$assets = getenv( 'EEXP_FIXTURE_ASSETS' );
	$assets = false === $assets || '' === $assets ? '../../modules/explainer/assets/' : $assets;

	$slab = array(
		'p1_step'          => '',
		'p1_label'         => 'What the air carries',
		'p1_title'         => 'Exhaust that fouls everything else',
		'p1_title_tag'     => 'h3',
		'p1_body'          => 'Grease, soot, moisture, lint and fiber arrive with the airstream — the load that closes a finned exchanger down.',
		'p1_image'         => array( 'url' => $images . 'lepido-contaminants.webp' ),
		'p1_loads_label'   => 'Carried in, carried straight back out',
		'p1_pill_style'    => 'dot',
		'p1_pills'         => array(
			array( 'text' => 'Grease' ),
			array( 'text' => 'Soot' ),
			array( 'text' => 'Moisture' ),
			array( 'text' => 'Lint' ),
			array( 'text' => 'Fibre' ),
			array( 'text' => 'Fumes' ),
		),

		'p2_step'          => '',
		'p2_label'         => 'What the geometry does',
		'p2_title'         => 'Particles are repelled, not trapped',
		'p2_title_tag'     => 'h3',
		'p2_body'          => 'Ample spacing between the coils creates an airflow pattern that carries particles straight through the unit instead of onto its surfaces.',
		'p2_image'         => array( 'url' => $images . 'prg-flow.webp' ),
		'p2_plate'         => 'yes',
		'p2_caption_left'  => 'Hot contaminated exhaust in',
		'p2_caption_right' => 'Cooled air out →',
		'p2_motes'         => 5,
		'p2_specs'         => array(
			array(
				'label' => 'Flow',
				'value' => '100% counter-current',
			),
			array(
				'label' => 'Circuiting',
				'value' => 'Multiple fluid patterns',
			),
			array(
				'label' => 'Transfer area',
				'value' => 'Matched to a conventional coil',
			),
		),
	);

	$ledger = array(
		'head_key'    => 'Across the same dirty airstream',
		'head_old'    => 'Conventional finned exchanger',
		'head_new'    => 'Lepido with PRG',
		'show_head'   => 'yes',
		'mark_winner' => 'yes',
		'rows'        => array(
			array(
				'key' => 'Coil surface',
				'old' => 'Tightly spaced fins, narrow passages',
				'new' => 'Finless, open coil with wide spacing',
			),
			array(
				'key' => 'Particle path',
				'old' => 'Grease and soot collect and stick',
				'new' => 'Particles pass through without clogging',
			),
			array(
				'key' => 'Pressure drop',
				'old' => 'Climbs as the unit fouls',
				'new' => 'Stays close to where it started',
			),
			array(
				'key' => 'Maintenance',
				'old' => 'Frequent cleaning to hold output',
				'new' => 'Drastically reduced intervention',
			),
			array(
				'key' => 'Heat transfer',
				'old' => 'Depends on fin area staying clean',
				'new' => 'Same surface area, held by counter-current flow',
			),
		),
	);

	// The slab twice, to prove the number control both ways on one page.
	$numbered            = $slab;
	$numbered['p1_step'] = '01';
	$numbered['p2_step'] = '02';

	$bare_slab     = new Slab_Fixture( $slab );

	$gradient                = $slab;
	$gradient['title_fill']  = 'gradient';
	$gradient_slab           = new Slab_Fixture( $gradient );

	$reveal                  = $slab;
	$reveal['title_fill']    = 'reveal';
	$reveal_slab             = new Slab_Fixture( $reveal );

	$solid_pills                  = $slab;
	$solid_pills['p1_pill_style'] = 'solid';
	$solid_slab                   = new Slab_Fixture( $solid_pills );
	$numbered_slab = new Slab_Fixture( $numbered );

	// And the slab with a picture behind the ink panel, under a veil, which is
	// the other correction. The background group control writes exactly this.
	$backed = '<style>.backed .eexp-panel--ink{background-image:url(' . $images . 'lepido-contaminants.webp);background-size:cover;background-position:center}.backed .eexp{--eexp-dim:.62}</style>';

	$backed_slab = new Slab_Fixture( $numbered );

	$ledger_widget = new Ledger_Fixture( $ledger );

	$plain_ledger  = new Ledger_Fixture(
		array_merge(
			$ledger,
			array(
				'mark_winner' => '',
				'show_head'   => '',
			)
		)
	);

	?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Split Explainer — browser fixture</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Urbanist:wght@500;600;700&display=swap">
<link rel="stylesheet" href="<?php echo esc_attr( $assets ); ?>css/split-explainer.css">
<style>
/*
 * The kit's job, not the widget's: the families and the section surface. The
 * widget inherits both, which is the whole point of leaving them out of the
 * module stylesheet.
 */
body{margin:0;background:#08121C;font:16px/1.6 "Plus Jakarta Sans",system-ui,sans-serif}
.host{padding:10% 24px;max-width:1440px;margin-inline:auto}
.eexp-heading,.eexp-step__num,.eexp-outs b{font-family:"Bebas Neue",Impact,sans-serif}
.eexp-chip,.eexp-label,.eexp-loads li,.eexp-loads__label,.eexp-specs b,.eexp-lhead span,
.eexp-flow__caption,.eexp-btn{font-family:"Urbanist",system-ui,sans-serif}
.marker{max-width:1440px;margin:0 auto;padding:0 24px;color:#4DCF8D;
  font:600 13px/1 "Urbanist",system-ui,sans-serif;letter-spacing:.08em;text-transform:uppercase}

/* A hostile theme, the same block the other harnesses carry. */
img{max-width:100%;height:auto}
.eexp img{object-fit:contain}
</style>
</head>
<body>
<p class="marker">Slab — step numbers empty, the default</p>
<div class="host"><?php echo $bare_slab->to_html(); // phpcs:ignore ?></div>

<p class="marker">Slab — gradient heading fill</p>
<div class="host"><?php echo $gradient_slab->to_html(); // phpcs:ignore ?></div>

<p class="marker">Slab — heading fills a word at a time</p>
<div class="host"><?php echo $reveal_slab->to_html(); // phpcs:ignore ?></div>

<p class="marker">Slab — filled pills</p>
<div class="host"><?php echo $solid_slab->to_html(); // phpcs:ignore ?></div>

<p class="marker">Slab — step numbers filled in</p>
<div class="host"><?php echo $numbered_slab->to_html(); // phpcs:ignore ?></div>

<?php echo $backed; // phpcs:ignore ?>
<p class="marker">Slab — a picture behind the ink panel, veiled at 62%</p>
<div class="host backed"><?php echo $backed_slab->to_html(); // phpcs:ignore ?></div>

<p class="marker">Ledger</p>
<div class="host"><?php echo $ledger_widget->to_html(); // phpcs:ignore ?></div>

<p class="marker">Ledger — no winner, no header row</p>
<div class="host"><?php echo $plain_ledger->to_html(); // phpcs:ignore ?></div>

<script src="<?php echo esc_attr( $assets ); ?>js/split-explainer.js"></script>
</body>
</html>
	<?php
}
